(function($) {
        $(function() {
            var isoCountries = [
				{ val: '', id: '', text: ''},
                { val: 'ARG', id: 'AR', text: 'Argentina'},
                { val: 'AUS', id: 'AU', text: 'Australia'},
                { val: 'AUT', id: 'AT', text: 'Austria'},
                { val: 'BHR', id: 'BH', text: 'Bahrain'},
                { val: 'BEL', id: 'BE', text: 'Belgium'},
                { val: 'BRA', id: 'BR', text: 'Brazil'},
                { val: 'BGR', id: 'BG', text: 'Bulgaria'},
                { val: 'CAN', id: 'CA', text: 'Canada'},
                { val: 'CHL', id: 'CL', text: 'Chile'},
                { val: 'CHN', id: 'CN', text: 'China'},
                { val: 'COL', id: 'CO', text: 'Colombia'},
                { val: 'HRV', id: 'HR', text: 'Croatia'},
                { val: 'CYP', id: 'CY', text: 'Cyprus'},
                { val: 'CZE', id: 'CZ', text: 'Czech Republic'},
                { val: 'DNK', id: 'DK', text: 'Denmark'},
                { val: 'DOM', id: 'DM', text: 'Dominica'},
                { val: 'SLV', id: 'SV', text: 'El Salvador'},
                { val: 'EST', id: 'EE', text: 'Estonia'},
                { val: 'FIN', id: 'FI', text: 'Finland'},
                { val: 'FRA', id: 'FR', text: 'France'},
//                { id: 'GF', text: 'French Guiana'},
//                { id: 'PF', text: 'French Polynesia'},
//                { id: 'TF', text: 'French Southern Territories'},
//                { id: 'GA', text: 'Gabon'},
//                { id: 'GM', text: 'Gambia'},
//                { id: 'GE', text: 'Georgia'},
//                { id: 'DE', text: 'Germany'},
//                { id: 'GH', text: 'Ghana'},
//                { id: 'GI', text: 'Gibraltar'},
//                { id: 'GR', text: 'Greece'},
//                { id: 'GL', text: 'Greenland'},
//                { id: 'GD', text: 'Grenada'},
//                { id: 'GP', text: 'Guadeloupe'},
//                { id: 'GU', text: 'Guam'},
//                { id: 'GT', text: 'Guatemala'},
//                { id: 'GG', text: 'Guernsey'},
//                { id: 'GN', text: 'Guinea'},
//                { id: 'GW', text: 'Guinea-Bissau'},
//                { id: 'GY', text: 'Guyana'},
//                { id: 'HT', text: 'Haiti'},
//                { id: 'HM', text: 'Heard Island & Mcdonald Islands'},
//                { id: 'VA', text: 'Holy See (Vatican City State)'},
//                { id: 'HN', text: 'Honduras'},
//                { id: 'HK', text: 'Hong Kong'},
//                { id: 'HU', text: 'Hungary'},
//                { id: 'IS', text: 'Iceland'},
//                { id: 'IN', text: 'India'},
//                { id: 'ID', text: 'Indonesia'},
//                { id: 'IR', text: 'Iran}, Islamic Republic Of'},
//                { id: 'IQ', text: 'Iraq'},
//                { id: 'IE', text: 'Ireland'},
//                { id: 'IM', text: 'Isle Of Man'},
//                { id: 'IL', text: 'Israel'},
//                { id: 'IT', text: 'Italy'},
//                { id: 'JM', text: 'Jamaica'},
//                { id: 'JP', text: 'Japan'},
//                { id: 'JE', text: 'Jersey'},
//                { id: 'JO', text: 'Jordan'},
//                { id: 'KZ', text: 'Kazakhstan'},
//                { id: 'KE', text: 'Kenya'},
//                { id: 'KI', text: 'Kiribati'},
//                { id: 'KR', text: 'Korea'},
//                { id: 'KW', text: 'Kuwait'},
//                { id: 'KG', text: 'Kyrgyzstan'},
//                { id: 'LA', text: "Lao People's Democratic Republic"},
//                { id: 'LV', text: 'Latvia'},
//                { id: 'LB', text: 'Lebanon'},
//                { id: 'LS', text: 'Lesotho'},
//                { id: 'LR', text: 'Liberia'},
//                { id: 'LY', text: 'Libyan Arab Jamahiriya'},
//                { id: 'LI', text: 'Liechtenstein'},
//                { id: 'LT', text: 'Lithuania'},
//                { id: 'LU', text: 'Luxembourg'},
//                { id: 'MO', text: 'Macao'},
//                { id: 'MK', text: 'Macedonia'},
//                { id: 'MG', text: 'Madagascar'},
//                { id: 'MW', text: 'Malawi'},
//                { id: 'MY', text: 'Malaysia'},
//                { id: 'MV', text: 'Maldives'},
//                { id: 'ML', text: 'Mali'},
//                { id: 'MT', text: 'Malta'},
//                { id: 'MH', text: 'Marshall Islands'},
//                { id: 'MQ', text: 'Martinique'},
//                { id: 'MR', text: 'Mauritania'},
//                { id: 'MU', text: 'Mauritius'},
//                { id: 'YT', text: 'Mayotte'},
//                { id: 'MX', text: 'Mexico'},
//                { id: 'FM', text: 'Micronesia, Federated States'},
//                { id: 'MD', text: 'Moldova'},
//                { id: 'MC', text: 'Monaco'},
//                { id: 'MN', text: 'Mongolia'},
//                { id: 'ME', text: 'Montenegro'},
//                { id: 'MS', text: 'Montserrat'},
//                { id: 'MA', text: 'Morocco'},
//                { id: 'MZ', text: 'Mozambique'},
//                { id: 'MM', text: 'Myanmar'},
//                { id: 'NA', text: 'Namibia'},
//                { id: 'NR', text: 'Nauru'},
//                { id: 'NP', text: 'Nepal'},
//                { id: 'NL', text: 'Netherlands'},
//                { id: 'AN', text: 'Netherlands Antilles'},
//                { id: 'NC', text: 'New Caledonia'},
//                { id: 'NZ', text: 'New Zealand'},
//                { id: 'NI', text: 'Nicaragua'},
//                { id: 'NE', text: 'Niger'},
//                { id: 'NG', text: 'Nigeria'},
//                { id: 'NU', text: 'Niue'},
//                { id: 'NF', text: 'Norfolk Island'},
//                { id: 'MP', text: 'Northern Mariana Islands'},
//                { id: 'NO', text: 'Norway'},
//                { id: 'OM', text: 'Oman'},
//                { id: 'PK', text: 'Pakistan'},
//                { id: 'PW', text: 'Palau'},
//                { id: 'PS', text: 'Palestinian Territory, Occupied'},
//                { id: 'PA', text: 'Panama'},
//                { id: 'PG', text: 'Papua New Guinea'},
//                { id: 'PY', text: 'Paraguay'},
//                { id: 'PE', text: 'Peru'},
//                { id: 'PH', text: 'Philippines'},
//                { id: 'PN', text: 'Pitcairn'},
//                { id: 'PL', text: 'Poland'},
//                { id: 'PT', text: 'Portugal'},
//                { id: 'PR', text: 'Puerto Rico'},
//                { id: 'QA', text: 'Qatar'},
//                { id: 'RE', text: 'Reunion'},
//                { id: 'RO', text: 'Romania'},
//                { id: 'RU', text: 'Russian Federation'},
//                { id: 'RW', text: 'Rwanda'},
//                { id: 'BL', text: 'Saint Barthelemy'},
//                { id: 'SH', text: 'Saint Helena'},
//                { id: 'KN', text: 'Saint Kitts And Nevis'},
//                { id: 'LC', text: 'Saint Lucia'},
//                { id: 'MF', text: 'Saint Martin'},
//                { id: 'PM', text: 'Saint Pierre And Miquelon'},
//                { id: 'VC', text: 'Saint Vincent And Grenadines'},
//                { id: 'WS', text: 'Samoa'},
//                { id: 'SM', text: 'San Marino'},
//                { id: 'ST', text: 'Sao Tome And Principe'},
//                { id: 'SA', text: 'Saudi Arabia'},
//                { id: 'SN', text: 'Senegal'},
//                { id: 'RS', text: 'Serbia'},
//                { id: 'SC', text: 'Seychelles'},
//                { id: 'SL', text: 'Sierra Leone'},
//                { id: 'SG', text: 'Singapore'},
//                { id: 'SK', text: 'Slovakia'},
//                { id: 'SI', text: 'Slovenia'},
//                { id: 'SB', text: 'Solomon Islands'},
//                { id: 'SO', text: 'Somalia'},
//                { id: 'ZA', text: 'South Africa'},
//                { id: 'GS', text: 'South Georgia And Sandwich Isl.'},
//                { id: 'ES', text: 'Spain'},
//                { id: 'LK', text: 'Sri Lanka'},
//                { id: 'SD', text: 'Sudan'},
//                { id: 'SR', text: 'Suriname'},
//                { id: 'SJ', text: 'Svalbard And Jan Mayen'},
//                { id: 'SZ', text: 'Swaziland'},
//                { id: 'SE', text: 'Sweden'},
//                { id: 'CH', text: 'Switzerland'},
//                { id: 'SY', text: 'Syrian Arab Republic'},
//                { id: 'TW', text: 'Taiwan'},
//                { id: 'TJ', text: 'Tajikistan'},
//                { id: 'TZ', text: 'Tanzania'},
//                { id: 'TH', text: 'Thailand'},
//                { id: 'TL', text: 'Timor-Leste'},
//                { id: 'TG', text: 'Togo'},
//                { id: 'TK', text: 'Tokelau'},
//                { id: 'TO', text: 'Tonga'},
//                { id: 'TT', text: 'Trinidad And Tobago'},
//                { id: 'TN', text: 'Tunisia'},
//                { id: 'TR', text: 'Turkey'},
//                { id: 'TM', text: 'Turkmenistan'},
//                { id: 'TC', text: 'Turks And Caicos Islands'},
//                { id: 'TV', text: 'Tuvalu'},
//                { id: 'UG', text: 'Uganda'},
//                { id: 'UA', text: 'Ukraine'},
//                { id: 'AE', text: 'United Arab Emirates'},
//                { id: 'GB', text: 'United Kingdom'},
//                { id: 'US', text: 'United States'},
//                { id: 'UM', text: 'United States Outlying Islands'},
//                { id: 'UY', text: 'Uruguay'},
//                { id: 'UZ', text: 'Uzbekistan'},
//                { id: 'VU', text: 'Vanuatu'},
//                { id: 'VE', text: 'Venezuela'},
//                { id: 'VN', text: 'Viet Nam'},
//                { id: 'VG', text: 'Virgin Islands}, British'},
//                { id: 'VI', text: 'Virgin Islands}, U.S.'},
//                { id: 'WF', text: 'Wallis And Futuna'},
//                { id: 'EH', text: 'Western Sahara'},
//                { id: 'YE', text: 'Yemen'},
//                { id: 'ZM', text: 'Zambia'},
//                { id: 'ZW', text: 'Zimbabwe'}
            ];
            
            function formatCountry (country) {
              if (!country.id) { return country.text; }
              var $country = $(
                '<span class="flag-icon flag-icon-'+ country.id.toLowerCase() +' flag-icon-squared"></span>' +
                '<span class="flag-text">'+ country.text+"</span>"
              );
              return $country;
            };
            
            //Assuming you have a select element with name country
            // e.g. <select name="name"></select>
            
            $("[name='country']").select2({
                placeholder: "Select a country",
				templateSelection: formatCountry,
				templateResult: formatCountry,
                data: isoCountries
            });
			
        });
})(jQuery);